### PR TITLE
Implement PEP8 Compliance

### PR DESCRIPTION
**Pull request by jnmclarty**
#12

...not done, just want to link to the issue.

### CODE REVIEW

**Comment by jnmclarty** [comment]
FYI @kissgyorgy

**Comment by kissgyorgy** [comment]
wow :smile: :+1:

**Comment by jnmclarty** [comment]
I know the camelcase has to go.  And it will.  I'd like a testing framework in place, to make sure stuff doesn't break as I refactor the stuff that spans multiple files...

**Comment by jnmclarty** [comment]
As GitHub indicates, all of this got merged, but per the actual repo the PEP8 branch has never been merged with master. I applied a squashed version of the PEP8 branch, in a single commit, on master.

**Comment by jnmclarty** [comment]
Huh! look at that, github stores a backup of an unmerged, deleted, branch.  cool.

**Pull request merged**
